# Generated by Django 4.1.7 on 2023-03-10 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('first_option', models.CharField(max_length=200)),
                ('second_option', models.CharField(max_length=200)),
                ('third_option', models.CharField(max_length=200)),
                ('fourth_option', models.CharField(max_length=200)),
                ('short_answer', models.TextField(max_length=1000)),
                ('correct_answer', models.CharField(max_length=200)),
                ('order', models.IntegerField()),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
        ),
    ]
