# Generated by Django 4.1.7 on 2023-03-10 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaltion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questions',
            options={'ordering': ('sort',), 'verbose_name': 'Questions', 'verbose_name_plural': 'Questions-plural'},
        ),
        migrations.AddField(
            model_name='questions',
            name='sort',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Sort'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='correct_answer',
            field=models.CharField(max_length=200, verbose_name='correct_answer'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='first_option',
            field=models.CharField(max_length=200, verbose_name='first_option'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='fourth_option',
            field=models.CharField(max_length=200, verbose_name='fourth_option'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='order',
            field=models.IntegerField(verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='question',
            field=models.CharField(max_length=200, verbose_name='question'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='second_option',
            field=models.CharField(max_length=200, verbose_name='second_option'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='short_answer',
            field=models.TextField(max_length=1000, verbose_name='short_answer'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='third_option',
            field=models.CharField(max_length=200, verbose_name='third_option'),
        ),
    ]
