# Generated by Django 4.1.7 on 2023-03-10 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaltion', '0002_alter_questions_options_questions_sort_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questions',
            options={'ordering': ('sort',), 'verbose_name': 'question', 'verbose_name_plural': 'question-plural'},
        ),
    ]
