# Generated by Django 4.1.7 on 2023-03-23 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaltion', '0003_alter_questions_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Active'),
        ),
    ]
