# Generated by Django 4.1.7 on 2023-03-23 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaltion', '0004_questions_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=250, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('active', models.BooleanField(default=False, verbose_name='Active')),
                ('sort', models.IntegerField(blank=True, default=0, null=True, verbose_name='Sort')),
                ('temperature_from', models.FloatField(blank=True, help_text='in ° C', null=True, verbose_name='Temperature_from')),
                ('temperature_to', models.FloatField(blank=True, help_text='in ° C', null=True, verbose_name='Temperature_to')),
            ],
            options={
                'verbose_name': 'wine',
                'verbose_name_plural': 'wine-plural',
                'ordering': ('sort',),
            },
        ),
        migrations.CreateModel(
            name='Winery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=250, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('sort', models.IntegerField(blank=True, default=0, null=True, verbose_name='Sort')),
            ],
            options={
                'verbose_name': 'Winery',
                'verbose_name_plural': 'Winery-plural',
                'ordering': ('sort',),
            },
        ),
        migrations.AlterModelOptions(
            name='questions',
            options={'ordering': ('sort',), 'verbose_name': 'Question', 'verbose_name_plural': 'question-plural'},
        ),
        migrations.CreateModel(
            name='Vintage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=0, verbose_name='Year')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('wine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vintages', to='transaltion.wine')),
            ],
        ),
    ]
