# Generated by Django 4.1.7 on 2023-03-23 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaltion', '0005_wine_winery_alter_questions_options_vintage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vintage',
            name='wine',
        ),
        migrations.DeleteModel(
            name='Winery',
        ),
        migrations.DeleteModel(
            name='Vintage',
        ),
        migrations.DeleteModel(
            name='Wine',
        ),
    ]
