# Generated by Django 3.2 on 2023-04-03 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaltion', '0007_auto_20230328_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='fourth_option_ar',
            field=models.CharField(max_length=200, null=True, verbose_name='fourth_option'),
        ),
        migrations.AddField(
            model_name='questions',
            name='fourth_option_en',
            field=models.CharField(max_length=200, null=True, verbose_name='fourth_option'),
        ),
        migrations.AddField(
            model_name='questions',
            name='short_answer_ar',
            field=models.TextField(max_length=1000, null=True, verbose_name='short_answer'),
        ),
        migrations.AddField(
            model_name='questions',
            name='short_answer_en',
            field=models.TextField(max_length=1000, null=True, verbose_name='short_answer'),
        ),
    ]
