# Generated by Django 3.2 on 2023-04-03 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaltion', '0009_auto_20230403_2101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='correct_answer_ar',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='correct_answer_en',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='fourth_option_ar',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='fourth_option_en',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='short_answer_ar',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='short_answer_en',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='third_option_ar',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='third_option_en',
        ),
    ]
