# Generated by Django 3.2 on 2023-04-03 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaltion', '0010_auto_20230403_2130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='active',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='correct_answer',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='fourth_option',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='order',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='short_answer',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='sort',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='third_option',
        ),
    ]
