# Generated by Django 3.2 on 2023-04-06 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaltion', '0012_vintage_wine_winery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vintage',
            name='wine',
        ),
        migrations.DeleteModel(
            name='Winery',
        ),
        migrations.DeleteModel(
            name='Vintage',
        ),
        migrations.DeleteModel(
            name='Wine',
        ),
    ]
